# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    russ_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

russ_group_controller:
  ros__parameters:
    joints:
      - shoulder_joint
      - upperarm_joint
      - forearm_joint
      - wrist1_joint
      - wrist2_joint
      - wrist3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity