# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - russ_group_controller

  russ_group_controller:
    type: FollowJointTrajectory
    joints:
      - shoulder_joint
      - upperarm_joint
      - forearm_joint
      - wrist1_joint
      - wrist2_joint
      - wrist3_joint
    action_ns: follow_joint_trajectory
    default: true